staging_folder = 'G:/Geoff/osmnx/data/staging'

urbanized_areas_shapefile_folder = 'G:/Geoff/osmnx/data/urbanized_areas/shapefiles'
urbanized_areas_graphml_folder = 'G:/Geoff/osmnx/data/urbanized_areas/graphml'
urbanized_areas_lists_folder = 'G:/Geoff/osmnx/data/urbanized_areas/node_edge_lists'
urbanized_areas_stats_folder = 'G:/Geoff/osmnx/data/urbanized_areas/stats'
urbanized_areas_cache_folder = 'G:/Geoff/osmnx/cache/urbanized_areas'

counties_shapefile_folder = 'G:/Geoff/osmnx/data/counties/shapefiles'
counties_graphml_folder = 'G:/Geoff/osmnx/data/counties/graphml'
counties_lists_folder = 'G:/Geoff/osmnx/data/counties/node_edge_lists'
counties_stats_folder = 'G:/Geoff/osmnx/data/counties/stats'
counties_cache_folder = 'G:/Geoff/osmnx/cache/counties'

cities_shapefile_folder = 'G:/Geoff/osmnx/data/cities/shapefiles'
cities_graphml_folder = 'G:/Geoff/osmnx/data/cities/graphml'
cities_lists_folder = 'G:/Geoff/osmnx/data/cities/node_edge_lists'
cities_stats_folder = 'G:/Geoff/osmnx/data/cities/stats'
cities_cache_folder = 'G:/Geoff/osmnx/cache/cities'

neighborhoods_shapefile_folder = 'G:/Geoff/osmnx/data/neighborhoods/shapefiles'
neighborhoods_graphml_folder = 'G:/Geoff/osmnx/data/neighborhoods/graphml'
neighborhoods_lists_folder = 'G:/Geoff/osmnx/data/neighborhoods/node_edge_lists'
neighborhoods_stats_folder = 'G:/Geoff/osmnx/data/neighborhoods/stats'
neighborhoods_cache_folder = 'G:/Geoff/osmnx/cache/neighborhoods'
